apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - wirepact.ch
  resources:
  - pkis
  verbs:
  - create
  - get
  - watch
- apiGroups:
  - apps
  - ''
  resources:
  - deployments
  - secrets
  - configmaps
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ''
  - admissionregistration.k8s.io
  resources:
  - services
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - patch
  - update
  - delete
- apiGroups:
  - wirepact.ch
  resources:
  - credentialtranslators
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - wirepact.ch
  resources:
  - pkis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
