apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: credentialtranslators.wirepact.ch
spec:
  group: wirepact.ch
  names:
    kind: CredentialTranslator
    listKind: CredentialTranslatorList
    plural: credentialtranslators
    singular: credentialtranslator
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.image
      name: Image
      priority: 1
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: Specification of the kubernetes object.
            properties:
              image:
                type: string
            type: object
        type: object
    served: true
    storage: true
