apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: meshparticipants.wirepact.ch
spec:
  group: wirepact.ch
  names:
    kind: MeshParticipant
    listKind: MeshParticipantList
    plural: meshparticipants
    singular: meshparticipant
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.deployment
      name: Deployment
      priority: 0
      type: string
    - jsonPath: .spec.service
      name: Service
      priority: 0
      type: string
    - jsonPath: .spec.translator
      name: Translator
      priority: 0
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              ingressPort:
                format: int32
                type: integer
              egressPort:
                format: int32
                type: integer
              translatorIngressPort:
                format: int32
                type: integer
              translatorEgressPort:
                format: int32
                type: integer
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              deployment:
                type: string
              targetPort:
                format: int32
                type: integer
              service:
                type: string
              translator:
                type: string
              env:
                additionalProperties:
                  type: string
                type: object
              args:
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
