apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pkis.wirepact.ch
spec:
  group: wirepact.ch
  names:
    kind: Pki
    listKind: PkiList
    plural: pkis
    singular: pki
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.dnsAddress
      name: DnsAddress
      priority: 0
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              dnsAddress:
                type: string
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              image:
                type: string
              port:
                format: int32
                type: integer
              secretName:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
