name: .NET Release

on:
  push:
    branches:
      - "main"

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.100

      - name: Setup Kustomize
        shell: bash
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        if: ${{env.BUILD_VERSION != ''}}
        with:
          context: ./
          file: ./Operator/Dockerfile
          push: true
          build-args: |
            BUILD_VERSION=${{ env.BUILD_VERSION }}
            COMMIT_SHA=${{ github.sha }}
          tags: |
            ghcr.io/wirepact/k8s-operator:latest
            ghcr.io/wirepact/k8s-operator:${{ github.sha }}
            ghcr.io/wirepact/k8s-operator:${{ env.BUILD_VERSION }}
