name: .NET Test

on:
  pull_request:
    branches:
      - '*'

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.100

      - name: Build
        run: dotnet build -c Release
